import "../styles/globals.css";
import Head from "next/head";
import { Provider } from "react-redux";
import store from "../store";
import Preloader from "../components/Preloader";
import { motion } from "framer-motion";
import { useEffect, useState } from "react";

function MyApp({ Component, pageProps, router }) {
  // set a timeout for the preloader to show
  const [showPreloader, setShowPreloader] = useState(true);

  useEffect(() => {
    setTimeout(() => {
      setShowPreloader(false);
    }, 6000);
  }, []);

  return (
    <>
      <Head>
        <title>Blogify</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link
          rel="stylesheet"
          href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.2.0/css/all.min.css"
          integrity="sha512-xh6O/CkQoPOWDdYTDqeRdPCVd1SpvCA9XXcUnZS2FmJNp1coAFzvtCN9BmamE+4aHK8yyUHUSCcJHgXloTyT2A=="
          crossOrigin="anonymous"
          referrerpolicy="no-referrer"
        />
      </Head>
      <Provider store={store}>
              <Component {...pageProps} />
            </Provider>

      {/* {
        // show the preloader if it's true
        showPreloader ? (
          <Preloader />
        ) : (
          <motion.div
            key={router.route}
            initial={{ opacity: 0.4, transform: "scale(0.9)" }}
            animate={{ opacity: 1, transform: "scale(1)" }}
          >
            <Provider store={store}>
              <Component {...pageProps} />
            </Provider>
          </motion.div>
        )
      } */}
    </>
  );
}

export default MyApp;
